### PR TITLE
Adding client side unit tests.

### PR DESCRIPTION
**Pull request by STeveShary**
Tim,

This is definitely gonna look a little complicated.  I have created some client-side unit tests for your jsScript.js code.  I am using four different tools to help:
- `Karma.js`:  This will run your code in a browser.  I am using phantom.js which runs in the background.  The file `karma.config.js` tells karma how to startup your javascript code to run it.
- `mocha.js`:  This is the testing framework that gives us the functions `describe(...)` and `it(...)`  This allows your tests to be run in a nice grouped fashion.
- `sinon.js`:  This is a mocking framework.  A mock is something that pretends to be something else.  I used it to mock socket.io.  So in your client code, we aren't going to actually make socket calls but your code thinks that I do.  You can see sinon in the top when I remake the `socket` variable in `movement.spec.js`
- `chai.js`:  This is a nice library that makes the testing assertions look nicer.  Chai allows me to write this line: `expect(2 + 2).to.equal(4);`

You should be able to run the tests with the line `npm test`   You should first need to install your npm dependencies by calling `npm install`.  One thing to note is that your tests should explain what your program should do.  You should write your tests to explain that.

This might cause more questions than solutions.  Feel free to ask me if you have any other questions.

### CODE REVIEW

**Comment by tbatty7** [comment]
Wow, thanks Steve! This looks great. My biggest challenge here was trying to figure out what tools I needed to learn to start doing unit tests. Looking forward to digging into these dependencies. Did you install them as dev dependencies or elsewhere on your computer?

**Comment by STeveShary** [comment]
All node dependencies are stored in the `node_modules` folder.   I removed that folder because you can re-populate it with the command `npm install`   All of the dependencies will be read in from `package.json` and then be downloaded into `node_modules`

**Comment by tbatty7** [comment]
Very cool.  I did not know you could do that.  Thanks!  And thanks so much for taking the time to fiddle with my code.  I know you have a lot of demands on your time.  I am very excited to look into this now.

**Comment by tbatty7** [comment]
Hi Steve,
I am having some difficulty with the tests passing when they should fail.  The one where you pass a string into the east function should fail, and it did not.  I have my server code console logging each command it receives, and it was receiving strings, but the test showing it should receive the number 1 passed.  I know it should fail because I have a console.log telling me what is being passed to Node on that .on event.  If I change the value of that test to false, it shows 1 failed test, but in the details it shows Call 1, Call2, Call3, etc failing until it gets to the test I am running.  Like it it running every test against the last one called.  If any of them pass, then it passes.  Any idea what is causing that?

**Comment by tbatty7** [comment]
Hey Steve, Just wanted to let you know I figured it out and am all set. Again, thanks so much for helping me with this. I really appreciate your willingness to share your skills. It's a blessing.

**Pull request merged**
